import "./globals.css";
import type { Metadata } from "next";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Providers } from "./context/Provider";
import toast, { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import Pulsation from "./components/atoms/Pulsation";

export const metadata: Metadata = {
  title: "Udemy Clone",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Toaster position="top-right" reverseOrder={false} />
          <Suspense fallback={<Pulsation />}>{children}</Suspense>
        </body>
      </Providers>
    </html>
  );
}
